import { wrapper } from "@/redux/store";
import { MantineProvider } from "@mantine/core";
import { Montserrat } from "@next/font/google";
import Head from "next/head";
import { Provider } from "react-redux";
import "styles/globals.css";

const montserrat = Montserrat({
  weight: ["400"],
  style: ["normal"],
  subsets: ["latin"],
});

export default function App({ Component, ...rest }) {
  const { store, props } = wrapper.useWrappedStore(rest);
  const { pageProps } = props;
  return (
    <>
      <Head>
        <title>Find Contest</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="title" content="Find Contest" />
        <meta
          name="description"
          content="Show upcoming and active competitive programming competitions."
        />
        <meta
          name="keywords"
          content="contest, coding, coding contest, competitive contest, competitive programming"
        />
        <meta name="robots" content="index, follow" />
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta name="language" content="English" />
        <meta name="revisit-after" content="1 days" />
        <meta name="author" content="Ashutosh Dash" />
        <meta property="og:title" content="Find Contest" />
        <meta
          property="og:description"
          content="Show upcoming and active competitive programming competitions."
        />
        <meta property="og:type" content="article" />
        <meta property="og:url" content="https://find-contest.vercel.app/" />
        <meta
          property="og:image"
          content="https://flaviocopes.com/website-banner.jpg"
        />
      </Head>
      <main>
        <Provider store={store}>
          <MantineProvider
            withGlobalStyles
            withNormalizeCSS
            theme={{
              /** Put your mantine theme override here */
              colorScheme: "light",
              fontFamily: "Montserrat!important",
            }}
          >
            <div className={montserrat.className}>
              <style jsx global>{`
                html {
                  font-family: ${montserrat.style.fontFamily};
                }
              `}</style>
              <Component {...pageProps} />
            </div>
          </MantineProvider>
        </Provider>
      </main>
    </>
  );
}
