import { wrapper } from "@/redux/store";
import { MantineProvider } from "@mantine/core";
import { Comfortaa } from "@next/font/google";
import Head from "next/head";
import { Provider } from "react-redux";
import "styles/globals.css";

const comfortaa = Comfortaa({
  weight: ["300", "400", "700"],
  style: ["normal"],
  subsets: ["latin"],
});

export default function App({ Component, ...rest }) {
  const { store, props } = wrapper.useWrappedStore(rest);
  const { pageProps } = props;
  return (
    <>
      <Head>
        <title>Find Contest</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Provider store={store}>
          <MantineProvider
            withGlobalStyles
            withNormalizeCSS
            theme={{
              /** Put your mantine theme override here */
              colorScheme: "light",
              fontFamily: "Comfortaa!important",
            }}
          >
            <div className={comfortaa.className}>
              <style jsx global>{`
                html {
                  font-family: ${comfortaa.style.fontFamily};
                }
              `}</style>
              <Component {...pageProps} />
            </div>
          </MantineProvider>
        </Provider>
      </main>
    </>
  );
}
